Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-09, with the labels that each got.

#2473 RC module documentation
  docs/en/modules/rc.md
Labels: documentation

#2485 Updated documentation for gpio.pulse
  docs/en/modules/gpio.md
Labels: documentation

#2483 Decode chunked responses case insensitve headers
  app/http/httpclient.c
Labels: bugfix

#2487 Add Getting Started page
  docs/css/extra.css
  docs/de/index.md
  docs/en/flash.md
  docs/en/getting-started.md
  docs/en/index.md
  docs/en/lfs.md
  docs/en/lua-developer-faq.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#2491 Better fix for HTTP header decode
  app/http/httpclient.c
Labels: enhancement
