Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-03, with the labels that each got.

#2283 Fix SNTP so that it retries DNS lookups if it needs to
  app/modules/sntp.c
Labels: bugfix

#2276 remove deprecated init functions in adxl345, am2320, bme280, bmp085, hdc1080, hmc58831, l3g4200d, HDC1000, lm92
  app/modules/adxl345.c
  app/modules/am2320.c
  app/modules/bme280.c
  app/modules/bmp085.c
  app/modules/hdc1080.c
  app/modules/hmc5883l.c
  app/modules/l3g4200d.c
  docs/en/modules/adxl345.md
  docs/en/modules/am2320.md
  docs/en/modules/bme280.md
  docs/en/modules/bmp085.md
  docs/en/modules/hdc1080.md
  docs/en/modules/hmc5883l.md
  docs/en/modules/l3g4200d.md
  lua_modules/hdc1000/HDC1000-example.lua
  lua_modules/hdc1000/HDC1000.lua
  lua_modules/hdc1000/README.md
  lua_modules/lm92/README.md
  lua_modules/lm92/lm92.lua
Labels: enhancement

#2269 Update to sdk 2.2
  Makefile
  app/Makefile
  app/driver/key.c
  app/include/arch/cc.h
  app/include/lwip/app/espconn.h
  app/include/lwip/app/espconn_tcp.h
  app/include/lwip/app/time.h
  app/include/lwip/mem.h
  app/include/lwip/sntp.h
  app/include/user_mbedtls.h
  app/include/user_version.h
  app/lwip/app/espconn.c
  app/lwip/app/espconn_tcp.c
  app/lwip/app/espconn_udp.c
  app/lwip/core/sntp.c
  app/lwip/core/tcp_in.c
  app/lwip/core/tcp_out.c
  app/mbedtls/app/espconn_mbedtls.c
  app/mbedtls/app/lwIPSocket.c
  app/modules/tls.c
  app/sqlite3/esp8266.c
  app/user/Makefile
  bin/.gitignore
  ld/nodemcu.ld
Labels: enhancement

#2298 Ignore lookup errors on sync request unless all lookups fail
  app/modules/sntp.c
  docs/en/modules/sntp.md
Labels: bugfix, enhancement

#2312 Patch SDK to 2.2.x branch, commit f8f27ce
  Makefile
Labels: bugfix

#2330 Added functions wifi.getcountry() and wifi.setcountry()
  app/modules/wifi.c
  docs/en/modules/wifi.md
Labels: enhancement
