Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-11, with the labels that each got.

#2528 Add examples to the "bit" module documentation
  docs/en/modules/bit.md
Labels: documentation

#2549 Fix documentation for gdbstub module
  docs/en/modules/gdbstub.md
Labels: bugfix, documentation

#2551 Changed ESP32 http user agent to "NodeMCU (ESP32)"
  components/modules/http.c
  docs/en/modules/http.md
  lua_examples/httptest.lua
Labels: ESP32

#2552 Default to "Release" code optimization level with -Os
  sdkconfig.defaults
Labels: ESP32

#2533 esp32: Add node.uptime() function using esp_timer_get_time()
  components/modules/node.c
  docs/en/modules/node.md
Labels: ESP32

#2517 Establish delay as event to trigger flushing of SPI buffer
  app/platform/u8x8_nodemcu_hal.c
Labels: bugfix, enhancement

#2544 Increase MQTT recv buffer size to support MTU 1500 (#2308)
  app/modules/mqtt.c
Labels: bugfix

#2550 ESP32: Add Sodium module
  components/modules/Kconfig
  components/modules/sodium.c
  docs/en/modules/sodium.md
  mkdocs.yml
Labels: ESP32

#2562 ESP32: Add SJSON module
  components/modules/Kconfig
  components/modules/sjson.c
  components/sjson/component.mk
  components/sjson/json_config.h
  components/sjson/jsonsl.c
  components/sjson/jsonsl.h
  docs/en/modules/sjson.md
  mkdocs.yml
Labels: ESP32

#2561 ESP32: Add time module
  components/modules/Kconfig
  components/modules/time.c
  docs/en/modules/time.md
  mkdocs.yml
Labels: ESP32

#2573 Always compile `app/crypto` folder (BLOOM modude depends on it)
  app/Makefile
Labels: bugfix

#2559 ESP32: add support for RS485
  components/base_nodemcu/uart.c
  components/platform/include/platform.h
  components/platform/platform.c
  docs/en/modules/uart.md
Labels: ESP32

#2571 MQTT: handle large/chunked/fragmented messages properly
  app/modules/mqtt.c
  app/mqtt/mqtt_msg.c
  app/mqtt/mqtt_msg.h
  docs/en/modules/mqtt.md
Labels: bugfix
