Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-08, with the labels that each got.

#2452 file: list now takes optional pattern for filtering
  app/modules/file.c
  docs/en/modules/file.md
Labels: enhancement

#2454 LFS: small tweaks to docs and examples
  docs/en/lfs.md
  lua_examples/lfs/_init.lua
  lua_examples/lfs/lfs_fragments.lua
Labels: documentation, enhancement

#2453 app/lua/luac_cross: WRAPCC CC here, too
  app/lua/luac_cross/Makefile
Labels: enhancement

#2450 create luac.cross.{integer|float}
  app/lua/luac_cross/Makefile
  local/lua/.gitignore
  tools/Makefile
Labels: enhancement

#2460 mention github desktop in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2463 FAQ update for io.write clarification
  docs/en/lua-developer-faq.md
Labels: documentation

#2458 LFS documentation and example updates
  docs/en/lfs.md
  lua_examples/lfs/HTTP_OTA.lua
  lua_examples/lfs/_init.lua
Labels: documentation

#2455 lua_examples/telnet changes
  lua_examples/telnet.lua
  lua_examples/telnet/README.md
  lua_examples/telnet/telnet.lua
Labels: enhancement

#2469 Fix #2430 node.input() not working
  app/lua/lua.c
Labels: bugfix
