Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-07, with the labels that each got.

#2417 New FTP module
  lua_modules/ftp/README.md
  lua_modules/ftp/ftpserver.lua
Labels: new feature, new module

#2416 New Telnet module
  lua_examples/telnet/README.md
  lua_examples/telnet/simple_telnet.lua
  lua_examples/telnet/telnet.lua
Labels: enhancement

#2423 Add checking of lua sources to travis build
  lua_examples/lfs/lfs_fragments.lua
  lua_examples/mqtt/mqtt_file.lua
  tools/pr-build.sh
Labels: bugfix

#2401 Espressif SDK v2.2.1
  Makefile
  README.md
  app/lwip/app/dhcpserver.c
  app/lwip/app/espconn.c
Labels: enhancement

#2432 Adding "LFS Quick Start" section in the documentation
  docs/en/lfs.md
Labels: documentation
