Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-04, with the labels that each got.

#2339 net socket documentation clarification
  docs/en/lua-developer-faq.md
Labels: documentation

#2334 Put each ICACHE_RAM_ATTR function in its own section.
  app/include/user_config.h
  ld/nodemcu.ld
Labels: enhancement

#2287 Refactor timer suspend portion of node.sleep (pmsleep)
  app/Makefile
  app/coap/coap_timer.c
  app/driver/key.c
  app/driver/spi.c
  app/driver/uart.c
  app/http/httpclient.c
  app/include/misc/dynarr.h
  app/include/pm/pmSleep.h
  app/include/pm/swtimer.h
  app/include/rtc/rtctime_internal.h
  app/include/swTimer/swTimer.h
  app/include/user_config.h
  app/include/user_modules.h
  app/lwip/core/mdns.c
  app/misc/Makefile
  app/misc/dyn_arr.c
  app/modules/cron.c
  app/modules/ds18b20.c
  app/modules/enduser_setup.c
  app/modules/mqtt.c
  app/modules/node.c
  app/modules/rotary.c
  app/modules/sntp.c
  app/modules/tmr.c
  app/modules/wifi.c
  app/modules/ws2812_effects.c
  app/net/nodemcu_mdns.c
  app/pm/pmSleep.c
  app/pm/swtimer.c
  app/smart/smart.c
  app/swTimer/Makefile
  app/swTimer/swTimer.c
  app/websocket/websocketclient.c
  docs/en/modules/node.md
  docs/en/modules/tmr.md
  sdk-overrides/include/osapi.h
Labels: enhancement

#2358 Update node.dsleep() to support longer deep sleep duration.
  app/modules/node.c
  docs/en/modules/node.md
Labels: enhancement

#2322 fix for ds18b20 negative decimals
  app/modules/ds18b20.c
Labels: bugfix
