Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-10, with the labels that each got.

#2508 Set stdout to unbuffered
  components/base_nodemcu/user_main.c
Labels: ESP32

#2513 Check os_realloc calls in cron module
  app/modules/cron.c
Labels: enhancement

#2515 Cron fixes, part 2 (+)
  app/lua/luac_cross/Makefile
  app/modules/cron.c
Labels: bugfix, enhancement

#2505 Optimise ROTable accesses and interface
  app/include/module.h
  app/lua/lauxlib.c
  app/lua/lbaselib.c
  app/lua/ldblib.c
  app/lua/lgc.c
  app/lua/linit.c
  app/lua/lmathlib.c
  app/lua/loadlib.c
  app/lua/lobject.h
  app/lua/lrodefs.h
  app/lua/lrotable.c
  app/lua/lrotable.h
  app/lua/lstring.c
  app/lua/lstrlib.c
  app/lua/ltable.c
  app/lua/ltablib.c
  app/lua/ltm.c
  app/lua/ltm.h
  app/lua/luac_cross/Makefile
  app/lua/luac_cross/liolib.c
  app/lua/luac_cross/loslib.c
  app/lua/luaconf.h
  app/lua/lvm.c
  app/modules/wifi_monitor.c
  app/uzlib/host/uz_unzip.c
Labels: enhancement

#2531 u8g2: include "large" fonts
  app/u8g2lib/Makefile
Labels: bugfix

#2520 Re-rename ENABLE_TIMER_SUSPEND to TIMER_SUSPEND_ENABLE in user_config.h
  app/include/user_config.h
  app/modules/tmr.c
Labels: bugfix

#2524 Add object-based file API to dev-esp32 branch
  components/modules/file.c
  docs/en/modules/file.md
Labels: ESP32
