Repository nodemcu/nodemcu-firmware, pull requests merged in 2018-05, with the labels that each got.

#2365 Bugfix: wifi.suspend() disabled message causing crash
  app/modules/wifi.c
Labels: bugfix

#2367 Add message indicating that node.sleep() was disabled during build.
  app/modules/node.c
Labels: bugfix

#2375 Added function node.getcpufreq()
  app/modules/node.c
  docs/en/modules/node.md
Labels: new feature

#2318 Dev wifi/wifi_eventmon malloc/free update
  app/modules/wifi.c
  app/modules/wifi_common.h
  app/modules/wifi_eventmon.c
Labels: enhancement

#2378 Set safe defaults for scan config
  app/modules/wifi.c
Labels: enhancement
