Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-12, with the labels that each got.

#2969 Sensor driver for BME680 sensor - update to version 3.5.9
  app/modules/bme680.c
  app/modules/bme680_defs.h
Labels: bugfix

#2953 Fixes for `ws2812` and `ws2812_effects`
  .gitignore
  app/modules/ws2812.c
  app/modules/ws2812.h
  app/modules/ws2812_effects.c
  lua_tests/mispec.lua
  lua_tests/mispec_ws2812.lua
  lua_tests/mispec_ws2812_2.lua
  lua_tests/mispec_ws2812_effects.lua
Labels: bugfix

#2915 Streaming support for hx711, round II
  app/modules/hx711.c
  docs/modules/hx711.md
Labels: enhancement, new feature

#2862 New `net.if.info` call to show LwIP information
  app/include/netif/wlan_lwip_if.h
  app/modules/net.c
  docs/modules/net.md
Labels: enhancement

#2975 lua module ds18b20: fixed missing forward declaration
  lua_modules/ds18b20/ds18b20.lua
Labels: bugfix

#2673 Initial version of software UART C module
  app/include/user_modules.h
  app/modules/softuart.c
  docs/modules/softuart.md
  mkdocs.yml
Labels: new module

#2905 DCC decoder module
  app/driver/NmraDcc.c
  app/include/driver/NmraDcc.h
  app/include/user_modules.h
  app/modules/dcc.c
  docs/modules/dcc.md
  lua_examples/dcc/dcc.lua
  mkdocs.yml
Labels: new module
