Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-06, with the labels that each got.

#2776 Fix issue with ADS1115 module
  app/modules/ads1115.c
  docs/modules/ads1115.md
Labels: bugfix

#2560 ESP32: Add option to set IP/dns config
  components/modules/wifi_ap.c
  components/modules/wifi_sta.c
  docs/modules/wifi.md
Labels: ESP32

#2739 ESP32: Pulse counter module released
  .gitignore
  components/modules/Kconfig
  components/modules/pulsecnt.c
  docs/modules/pulsecnt.md
Labels: ESP32

#2807 Update LFS introduction
  docs/getting-started.md
Labels: documentation

#2790 Add luacheck config and configuration for Travis CI
  .travis.yml
  CONTRIBUTING.md
  tools/luacheck_config.lua
  tools/luacheck_config_helper.lua
  tools/travis/localua.sh
  tools/travis/run-luacheck.sh
Labels: enhancement
