Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-01, with the labels that each got.

#2609 fix number2integer conversion in ESP8266 for floating-point builds
  app/lua/luaconf.h
Labels: bugfix

#2605 fix number2integer conversion in ESP32
  components/lua/luaconf.h
Labels: ESP32, bugfix

#2615 fix memory leak in http one-shot requests
  components/modules/http.c
Labels: ESP32, bugfix

#2610 ESP32: fix memory leak in encoder.fromHex and avoid use luaM_free
  components/modules/encoder.c
Labels: ESP32, bugfix

#2607 ESP32 crypto module
  components/modules/Kconfig
  components/modules/crypto.c
  docs/modules/crypto.md
  mkdocs.yml
Labels: ESP32, new module

#2617 ESP8266: fix memory leak in encoder.fromHex and avoid use luaM_free
  app/modules/encoder.c
Labels: bugfix

#2623 Compilation fix
  components/modules/mqtt.c
Labels: ESP32, bugfix

#2603 Expunge integer timers
  app/modules/tmr.c
  docs/modules/tmr.md
Labels: enhancement

#2629 ESP32: MQTT module rewrite
  components/base_nodemcu/include/lnodeaux.h
  components/base_nodemcu/lnodeaux.c
  components/modules/mqtt.c
  docs/modules/mqtt.md
Labels: ESP32

#2637 ESP32: node.output()
  components/modules/node.c
Labels: ESP32
