Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-08, with the labels that each got.

#2869 Update ESP32 toolchain
  Makefile
Labels: ESP32

#2852 Fix enduser_setup default POST request
  app/modules/enduser_setup.c
Labels: bugfix

#2874 Be more assertive in the TLS documentation
  docs/modules/http.md
  docs/modules/mqtt.md
  docs/modules/tls.md
Labels: documentation

#2830 Extend node.info
  .gitignore
  Makefile
  app/include/user_version.h
  app/modules/node.c
  app/user/user_main.c
  docs/build.md
  docs/modules/node.md
  tools/update_buildinfo.sh
Labels: enhancement

#2877 Update .travis.yml
  .travis.yml
Labels: enhancement

#2855 Support eth boards without power pin, extend docs
  components/modules/eth.c
  docs/modules/eth.md
Labels: ESP32, bugfix, documentation
