Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-02, with the labels that each got.

#2643 Tell the truth about DNS in TLS module
  app/modules/tls.c
  docs/modules/tls.md
Labels: enhancement

#2646 Increase http timeout 10s -> 60s
  app/http/httpclient.h
  docs/modules/http.md
Labels: enhancement

#2644 Add support for SDMMC cards in SD-SPI mode
  components/fatfs/diskio.c
  components/fatfs/fatfs_config.h
  components/fatfs/myfatfs.c
  components/modules/sdmmc.c
  components/modules/spi_master.c
  docs/modules/sdmmc.md
  docs/modules/spi.md
  docs/sdcard.md
Labels: ESP32

#2658 Fix typo in example (parameters were mixed)
  docs/lua-modules/ftpserver.md
Labels: bugfix, documentation

#2661 Bugfix/2632 luaccrash
  app/uzlib/uzlib_deflate.c
Labels: bugfix

#2657 mqtt: add ceritificate handling to support server verification and mutual authentication
  components/modules/mqtt.c
  docs/modules/mqtt.md
Labels: ESP32

#2654 Minor fix to telnet Lua example and ftpserver Lua module
  lua_examples/telnet/telnet.lua
  lua_modules/ftp/ftpserver.lua
Labels: bugfix

#2650 A generic fifo and fifosock wrapper, under telnet and http server
  docs/lua-modules/fifo.md
  docs/lua-modules/fifosock.md
  docs/lua-modules/httpserver.md
  lua_examples/telnet/telnet.lua
  lua_modules/fifo/fifo.lua
  lua_modules/fifo/fifosock.lua
  lua_modules/fifo/fifosocktest.lua
  lua_modules/http/http-example.lua
  lua_modules/http/httpserver.lua
  mkdocs.yml
Labels: new feature

#2497 Initial version of code to support multiple hardware timers
  app/modules/gpio_pulse.c
  app/platform/hw_timer.c
Labels: new feature

#2641 ESP8266: add flash baudrate environment variable to Makefile and preset for ESP8285
  Makefile
Labels: enhancement

#2674 mqtt: raise MQTT_CONNECT_TIMEOUT
  app/modules/mqtt.c
Labels: enhancement

#2631 ESP32: remove use of luaM_free in file module
  components/base_nodemcu/include/lnodeaux.h
  components/base_nodemcu/lnodeaux.c
  components/modules/file.c
Labels: ESP32

#2679 DHT11 read sometimes failed with checksum error
  app/dht/dht.c
Labels: bugfix
