Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-09, with the labels that each got.

#2793 Add streaming support for hx711 device
  app/modules/hx711.c
  docs/modules/hx711.md
Labels: enhancement, new feature

#2927 Fix the ug8 and ucg modules broken by eaac369.
  components/modules/u8g2.c
  components/modules/ucg.c
Labels: ESP32, bugfix

#2929 Deprecate crypto.to{Hex,Base64}
  app/modules/crypto.c
  docs/modules/crypto.md
Labels: enhancement
