Repository nodemcu/nodemcu-firmware, pull requests merged in 2019-07, with the labels that each got.

#2815 Improved crypto module for ESP32, now with HMAC
  components/modules/Kconfig
  components/modules/crypto.c
  docs/modules/crypto.md
Labels: ESP32, enhancement

#2818 Fix unref default file descriptor while still in use
  app/modules/file.c
Labels: bugfix

#2812 OTA support for ESP32
  components/modules/Kconfig
  components/modules/otaupgrade.c
  docs/modules/otaupgrade.md
Labels: ESP32, new feature

#2826 Video walk through of build process
  docs/build.md
Labels: ESP32, documentation, enhancement

#2825 Fix net module losing TCP data.
  components/modules/net.c
Labels: ESP32, bugfix

#2827 Update enduser_setup.html.gz.def.h
  app/modules/enduser_setup/enduser_setup.html.gz.def.h
Labels: bugfix

#2832 fix rounding in ws2812:buffer:mix
  app/modules/ws2812.c
Labels: bugfix

#2829 Fix net module data loss & RTOS task unsafety
  components/base_nodemcu/user_main.c
  components/modules/net.c
  components/task/Kconfig
  components/task/include/task/task.h
  components/task/task.c
Labels: ESP32, bugfix

#2822 MQTT tweaks
  app/modules/mqtt.c
  docs/modules/mqtt.md
Labels: enhancement

#2837 Minor esp32 fixes
  components/base_nodemcu/uart.c
  components/task/task.c
Labels: ESP32, bugfix

#2820 Esp32 eth
  components/modules/Kconfig
  components/modules/eth.c
  docs/modules/eth.md
  mkdocs.yml
Labels: ESP32, new module

#2856 Fix espconn.h override on Windows
  sdk-overrides/include/espconn.h
Labels: bugfix

#2851 Example Lua module for coroutining
  docs/lua-modules/cohelper.md
  lua_modules/cohelper/README.md
  lua_modules/cohelper/cohelper.lua
Labels: new module

#2860 net docs: clarify DNS callbacks
  docs/modules/net.md
Labels: documentation

#2700 sntp: simplify and tidy a bit
  app/modules/sntp.c
Labels: bugfix

#2861 Lost fixes to nodemcu-partition.py
  tools/nodemcu-partition.py
Labels: bugfix
