Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-06, with the labels that each got.

#3139 Lost fix to nodemcu-partition.py (take 2)
  tools/nodemcu-partition.py
Labels: bugfix

#3133 Make the telnet example an Lua module
  docs/lua-modules/telnet.md
  lua_examples/telnet/README.md
  lua_examples/telnet/telnet_fifosock.lua
  lua_modules/ftp/ftpserver.lua
  lua_modules/telnet/README.md
  lua_modules/telnet/telnet.lua
  mkdocs.yml
Labels: enhancement

#3157 fix a memory leak in ws2812_buffer_shift
  app/modules/ws2812.c
Labels: bugfix

#3163 Implement panic call handling for all modules
  .gdbinitlua
  app/lua/lauxlib.c
  app/lua/lauxlib.h
  app/lua/ldebug.c
  app/lua/lflash.c
  app/lua/lnodemcu.c
  app/lua/lnodemcu.h
  app/lua/lobject.h
  app/lua/lua.h
  app/lua53/lauxlib.c
  app/lua53/lauxlib.h
  app/lua53/llimits.h
  app/lua53/lnodemcu.c
  app/lua53/lnodemcu.h
  app/lua53/lua.c
  app/lua53/lua.h
  app/lua53/lundump.h
  app/modules/ads1115.c
  app/modules/bme280.c
  app/modules/bme680.c
  app/modules/cron.c
  app/modules/crypto.c
  app/modules/dcc.c
  app/modules/enduser_setup.c
  app/modules/file.c
  app/modules/gpio.c
  app/modules/gpio_pulse.c
  app/modules/http.c
  app/modules/hx711.c
  app/modules/node.c
  app/modules/pcm.c
  app/modules/pipe.c
  app/modules/rotary.c
  app/modules/sntp.c
  app/modules/softuart.c
  app/modules/somfy.c
  app/modules/switec.c
  app/modules/tcs34725.c
  app/modules/tls.c
  app/modules/tmr.c
  app/modules/websocket.c
  app/modules/wifi.c
  app/modules/wifi_eventmon.c
  app/modules/wifi_monitor.c
  app/modules/wps.c
  app/pcm/pcm_core.c
  app/platform/platform.c
  app/pm/pmSleep.c
  app/pm/swtimer.c
  app/spiffs/nodemcu_spiffs.h
  app/spiffs/spiffs.c
  app/spiffs/spiffs_nucleus.c
  app/spiffs/spiffs_nucleus.h
  app/u8g2lib/u8x8_d_fbrle.c
  lua_modules/liquidcrystal/lc-gpio4bit.lua
  lua_modules/liquidcrystal/lc-gpio8bit.lua
  lua_modules/liquidcrystal/lc-i2c4bit.lua
  lua_modules/liquidcrystal/liquidcrystal.lua
Labels: enhancement

#3112 Ads1115 module minor cleanup
  app/modules/ads1115.c
Labels: enhancement

#3161 rtctime: try harder to speak in integers
  app/modules/rtctime.c
Labels: enhancement

#3184 Fixed conflict in documentation and example for method newChannel()
  docs/modules/ledc.md
Labels: ESP32, documentation
