Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-07, with the labels that each got.

#3195 Fixed esp-lwip breaking change on dns_getserver
  components/modules/net.c
Labels: ESP32

#3199 Fix of string.format("%.0f")
  app/libc/stdio.c
Labels: bugfix

#3100 ESP32: External modules
  .gitignore
  Makefile
  components/base_nodemcu/include/module.h
  components/modules/.gitignore
  docs/modules/extmods.md
  mkdocs.yml
  tools/extmod/component.mk.template
  tools/extmod/example/helloworld.c
  tools/extmod/extmod.sh
  tools/extmod/read_ini.sh
Labels: ESP32, enhancement
