Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-09, with the labels that each got.

#3260 Don't allocate flash to SPIFFS that is reserved by the system.
  app/modules/node.c
  app/user/user_main.c
  tools/nodemcu-partition.py
Labels: bugfix

#3168 Makes lfs/_init.lua compatible with Lua 5.3
  lua_examples/lfs/_init.lua
  tools/luacheck_config.lua
Labels: bugfix

#3104 SoftUART module fixes and code simplification
  app/modules/softuart.c
  docs/modules/softuart.md
Labels: bugfix, enhancement

#3267 Fixes `net.ifinfo` failure
  app/modules/net.c
Labels: bugfix

#3263 Fixes broken `tmr.alarm`
  app/modules/tmr.c
  docs/modules/tmr.md
Labels: bugfix

#3270 Adding '+' flag to string.format
  app/libc/stdio.c
Labels: enhancement

#3280 Fix problem reading files a multiple of 128 bytes long
  app/modules/file.c
Labels: bugfix

#3275 Handle tcp fragmentation and also fix XSS problem.
  app/modules/enduser_setup.c
  app/modules/enduser_setup/enduser_setup.html
  app/modules/enduser_setup/enduser_setup.html.gz.def.h
  app/modules/enduser_setup/enduser_setup_apple.html
  docs/modules/enduser-setup.md
Labels: bugfix

#3282 Improve the enduser setup experience by triggering captive portal detection.
  app/include/user_config.h
  app/modules/enduser_setup.c
  app/modules/enduser_setup/enduser_setup.html
  app/modules/enduser_setup/enduser_setup.html.gz.def.h
  docs/modules/enduser-setup.md
Labels: enhancement

#3300 crypto: remove toHex and toBase64
  app/modules/crypto.c
  docs/modules/crypto.md
Labels: breaking change
