Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-08, with the labels that each got.

#3201 Fix bthci compilation issue
  components/base_nodemcu/user_main.c
  components/modules/bthci.c
Labels: ESP32, bugfix

#3210 Dht negative
  app/dht/dht.c
Labels: bugfix

#3236 Add support to set the clock rate and have sntp use it.
  app/include/rtc/rtctime.h
  app/modules/rtctime.c
  app/modules/sntp.c
  docs/modules/rtctime.md
Labels: enhancement

#3242 mqtt: fix connfail callback
  app/modules/mqtt.c
Labels: bugfix

#3135 Kconfig: rename LUA_MODULE_* to NODEMCU_CMODULE_*
  components/base_nodemcu/include/module.h
  components/modules/Kconfig
  components/modules/bthci.c
  components/modules/component.mk
  components/modules/u8g2.c
  components/modules/ucg.c
  components/platform/Kconfig
  components/platform/include/user_version.h
  components/u8g2/u8g2.kconfig
  components/ucg/ucg.kconfig
  docs/extn-developer-faq.md
Labels: ESP32

#3258 [docs][minor] Fix filename of luac.cross in upload.md
  docs/upload.md
Labels: documentation

#3111 Implementing optional parameter `restart` to tmr:start()
  app/modules/tmr.c
  docs/modules/tmr.md
Labels: documentation, enhancement
