Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-05, with the labels that each got.

#3086 esp32: Correct level value in gpio.trig() callback (#2883)
  components/modules/gpio.c
Labels: breaking change, bugfix

#3093 u8g2: Fix name of updateDisplay export
  app/modules/u8g2.c
Labels: bugfix

#2854 net_info module - ping function
  app/include/user_config.h
  app/modules/net.c
  app/modules/net_ping.c
  app/modules/net_ping.h
  docs/modules/net.md
Labels: new module

#3091 Fix for #3089 - update hook after updating gpio bits
  app/platform/platform.c
Labels: bugfix

#2985 Fix binary and chunked HTTP downloads. Add diffs from @anod221.
  app/http/httpclient.c
  app/http/httpclient.h
  app/modules/http.c
Labels: bugfix

#3099 esp32: Expose gpio_set_drive_capability API to Lua
  components/modules/gpio.c
  docs/modules/gpio.md
Labels: ESP32, enhancement

#3088 ESP32: JTAG debugging quick guide for Linux
  docs/debug.md
  docs/img/cjmcu-232h.png
  mkdocs.yml
Labels: ESP32, documentation, enhancement
