Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-02, with the labels that each got.

#3022 Clarify LFS size build info means capacity
  app/modules/node.c
  tools/update_buildinfo.sh
Labels: enhancement

#3010 document tls.cert.auth
  app/modules/tls.c
  docs/modules/tls.md
Labels: documentation

#3026 No banner
  app/include/user_config.h
  app/lua/lua.c
Labels: enhancement

#3041 Documentation fixes for pipe
  docs/modules/pipe.md
  mkdocs.yml
Labels: documentation

#3029 Fix timing of softuart module RX
  app/modules/softuart.c
Labels: bugfix

#3042 Document that and why the sqlight3 module does not work currently
  docs/modules/sqlite3.md
Labels: documentation

#3047 Correct wifi auth types for esp32
  docs/modules/wifi.md
Labels: documentation
