Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-10, with the labels that each got.

#3308 Don't free a ref of zero -- bad things happen...
  app/modules/gpio_pulse.c
Labels: bugfix

#3171 Improved startup performance and measurement tools.
  app/include/user_config.h
  app/lua53/lua.c
  app/modules/file.c
  app/modules/node.c
  app/platform/platform.c
  app/platform/platform.h
  app/spiffs/nodemcu_spiffs.h
  app/spiffs/spiffs.c
  app/user/user_main.c
  docs/modules/node.md
Labels: enhancement, new feature

#3303 Fix the initialization of the wifi default hostname.
  app/include/user_config.h
  app/modules/wifi.c
  app/user/user_main.c
Labels: enhancement

#3203 add wiegand module
  app/include/user_modules.h
  app/modules/wiegand.c
  docs/modules/wiegand.md
  mkdocs.yml
  tools/luacheck_config.lua
Labels: new module

#3295 Fix pipe unread (#3155)
  app/modules/pipe.c
Labels: bugfix

#3197 add mcp23017 Lua module
  docs/lua-modules/mcp23017.md
  lua_examples/mcp23017/mcp23017_example.lua
  lua_modules/mcp23017/README.md
  lua_modules/mcp23017/mcp23017.lua
  mkdocs.yml
Labels: new module
