Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-01, with the labels that each got.

#2991 Minor typo and wording fixes
  app/include/user_config.h
Labels: documentation

#2992 DS18B20 - CRC check added to lua module, minor optimization; change of ow module example
  docs/modules/ow.md
  lua_modules/ds18b20/ds18b20.lua
Labels: enhancement

#2996 Fixes to softuart module
  app/modules/softuart.c
Labels: bugfix

#2906 expose cpu ccount registrer as platform and lua_node functions
  app/modules/tmr.c
  app/platform/platform.h
  docs/modules/tmr.md
Labels: enhancement

#2998 Auto-install SDK if user forgot to. (#2994)
  Makefile
Labels: ESP32, enhancement

#2999 ESP32 Makefile: Auto-detect CPU architecture
  Makefile
Labels: ESP32, enhancement
