Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-03, with the labels that each got.

#3013 Lua module for Gossip protocol
  docs/lua-modules/gossip.md
  lua_examples/gossip_example.lua
  lua_modules/gossip/README.md
  lua_modules/gossip/gossip.lua
  lua_modules/gossip/gossip_tests.lua
  mkdocs.yml
Labels: new module

#2986 WIP: MQTT fixes
  app/modules/mqtt.c
  app/mqtt/mqtt_msg.c
  app/mqtt/mqtt_msg.h
  docs/modules/mqtt.md
Labels: bugfix

#3048 Update getting-started docs hrefs for LFS examples
  docs/getting-started.md
Labels: documentation
