Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-11, with the labels that each got.

#3322 Fix ftpserver documentation and some formating in httpserver.md
  docs/lua-modules/ftpserver.md
  docs/lua-modules/httpserver.md
Labels: bugfix, documentation

#3325 BME280 Lua module - `(config[3] & 0xFC) | BME280_FORCED_MODE` workaround bug fix
  lua_modules/bme280/bme280.lua
Labels: bugfix

#3327 Allow turning off softwd again as documented
  app/modules/tmr.c
  tests/NTest_tmr.lua
Labels: bugfix

#3324 Basic hardware test examples
  tests/NTest/NTest.lua
  tests/NTest_adc_env.lua
  tests/NTest_gpio_env.lua
  tests/NodeMCU_Test_Environment.rst
Labels: enhancement

#3333 Doc fixes
  CONTRIBUTING.md
  README.md
  docs/build.md
  docs/getting-started.md
  docs/index.md
  docs/lua-modules/bme280.md
  docs/lua-modules/liquidcrystal.md
  docs/lua53.md
  docs/modules/file.md
  docs/modules/net.md
  docs/modules/ucg.md
  docs/modules/wifi.md
  docs/modules/ws2812.md
  lua_modules/bme280/bme280.lua
Labels: documentation
