Repository nodemcu/nodemcu-firmware, pull requests merged in 2020-04, with the labels that each got.

#3060 Networking rampage and accumulated fixes
  app/http/httpclient.c
  app/include/lwip/app/espconn.h
  app/include/sys/espconn_mbedtls.h
  app/include/user_mbedtls.h
  app/lwip/app/espconn.c
  app/lwip/app/espconn_mdns.c
  app/lwip/app/espconn_tcp.c
  app/lwip/app/espconn_udp.c
  app/mbedtls/app/espconn_mbedtls.c
  app/mbedtls/app/espconn_secure.c
  app/mbedtls/app/lwIPSocket.c
  app/mbedtls/platform/mbedtls_net.c
  app/modules/mqtt.c
  app/modules/net.c
  app/modules/tls.c
  app/websocket/websocketclient.c
  docs/modules/mqtt.md
  docs/modules/net.md
  docs/modules/tls.md
  tools/luacheck_config.lua
Labels: bugfix, enhancement

#2974 add LiquidCrystal lua module
  docs/lua-modules/liquidcrystal.md
  lua_modules/liquidcrystal/lc-gpio4bit.lua
  lua_modules/liquidcrystal/lc-gpio8bit.lua
  lua_modules/liquidcrystal/lc-i2c4bit.lua
  lua_modules/liquidcrystal/liquidcrystal.lua
  mkdocs.yml
Labels: enhancement, new module

#3069 HTML for Apple devices to mitigate POST fragmentation
  app/modules/enduser_setup/enduser_setup_apple.html
  docs/modules/enduser-setup.md
Labels: bugfix

#3076 fix #2565 by inverting the grb2hsv argcheck condition
  app/modules/color_utils.c
Labels: bugfix

#3072 esp32: Unref gpio.trig callbacks when type=INTR_DISABLE (#2880)
  components/modules/gpio.c
  docs/modules/gpio.md
Labels: ESP32, bugfix

#3083 Address build error when path contains whitespace
  Makefile
Labels: ESP32
