Repository nodemcu/nodemcu-firmware, pull requests merged in 2021-09, with the labels that each got.

#3437 Dev esp32 add eth.set_ip() method
  components/modules/eth.c
  docs/modules/eth.md
Labels: new feature, ESP32

#3463 Bump to Ubuntu 20.04
  .github/workflows/build.yml
Labels: CI

#3464 Update link to `flashchips.h` in docs/flash.md
  docs/flash.md
Labels: documentation

#3461 ow: add alarm scans and timing tweaking
  app/driver/onewire.c
  app/include/driver/onewire.h
  app/modules/ow.c
  docs/modules/ow.md
Labels: enhancement, new feature
