Repository nodemcu/nodemcu-firmware, pull requests merged in 2021-04, with the labels that each got.

#3399 Document node.setonerror()
  docs/modules/node.md
Labels: documentation

#3411 Update u8g2 doc (add extra online XBM format converter)
  docs/modules/u8g2.md
Labels: documentation

#3413 Add node.bootreason
  components/lua/lauxlib.c
  components/lua/lauxlib.h
  components/modules/node.c
  docs/modules/node.md
Labels: ESP32, new feature

#3425 Fix i2c docs formatting
  docs/modules/i2c.md
Labels: documentation

#3428 Fix adc, i2c, file, tmr docs esp32
  docs/modules/adc.md
  docs/modules/file.md
  docs/modules/i2c.md
  docs/modules/tmr.md
Labels: ESP32, bugfix, documentation
