Repository nodemcu/nodemcu-firmware, pull requests merged in 2021-02, with the labels that each got.

#3400 Add note about GPL
  docs/modules/am2320.md
Labels: documentation

#3398 handle impact of excluding pixbuf from build
  app/modules/apa102.c
  app/modules/tm1829.c
  app/modules/ws2801.c
  app/modules/ws2812.c
  app/modules/ws2812_effects.c
  docs/modules/apa102.md
  docs/modules/tm1829.md
  docs/modules/ws2801.md
  docs/modules/ws2812-effects.md
  docs/modules/ws2812.md
Labels: documentation, enhancement

#3390 Add uart.txflush() API (ESP32)
  components/base_nodemcu/uart.c
  docs/modules/node.md
  docs/modules/uart.md
Labels: ESP32, new feature
