Repository nodemcu/nodemcu-firmware, pull requests merged in 2021-01, with the labels that each got.

#3360 First round of mqtt fixes
  app/modules/mqtt.c
  app/mqtt/mqtt_msg.h
  app/mqtt/msg_queue.c
  app/mqtt/msg_queue.h
  docs/modules/mqtt.md
Labels: bugfix

#3365 httpserver: fix memory leak
  lua_modules/http/httpserver.lua
Labels: bugfix

#3366 Ensure tmr ref is valid before calling tmr callback
  components/modules/tmr.c
Labels: ESP32

#3363 Add node.osoutput() method for esp32
  components/modules/node.c
  docs/modules/node.md
Labels: ESP32, enhancement

#3158 LED strip refactor
  app/include/user_modules.h
  app/modules/apa102.c
  app/modules/pixbuf.c
  app/modules/pixbuf.h
  app/modules/tm1829.c
  app/modules/ws2801.c
  app/modules/ws2812.c
  app/modules/ws2812.h
  app/modules/ws2812_effects.c
  docs/modules/apa102.md
  docs/modules/pixbuf.md
  docs/modules/tm1829.md
  docs/modules/ws2812.md
  tests/NTest_pixbuf.lua
  tests/NTest_ws2812.lua
  tools/luacheck_config.lua
Labels: enhancement, new module

#3357 fix regression in luaL_typerror and Change NTest so it can run tests on the host emulating node.task.post
  .github/workflows/build.yml
  app/lua/lauxlib.c
  tests/NTest/NTest.lua
  tests/NTest/NTest_NTest.lua
  tests/NTest_lua.lua
Labels: bugfix, enhancement

#3368 More LED fixes
  app/modules/apa102.c
  app/modules/ws2812.c
  app/platform/cpu_esp8266_irq.h
Labels: bugfix

#3353 More NTest prep work for eventual test harness
  tests/.gitattributes
  tests/NTest/NTest.lua
  tests/NTest/NTest.md
  tests/NTest/NTest_NTest.lua
  tests/NTest_adc_env.lua
  tests/NTest_file.lua
  tests/NTest_gpio_env.lua
  tests/NTest_tmr.lua
  tests/NodeMCU_Test_Environment.md
  tests/README.md
  tests/expectnmcu/core.tcl
  tests/expectnmcu/pkgIndex.tcl
  tests/expectnmcu/xfer.tcl
  tests/tap-driver.expect
  tests/utils/NTestTapOut.lua
Labels: enhancement

#3370 Add node.sleep() to ESP32 API
  components/base_nodemcu/uart.c
  components/modules/node.c
  docs/modules/gpio.md
  docs/modules/node.md
  docs/modules/uart.md
Labels: ESP32, new feature

#3359 Add board documentation [WIP]
  tests/HardwareTestHarness.md
  tests/README.md
  tests/Test-harness-schematic-v1.pdf
Labels: documentation

#3377 Fix ESP32 i2c timeout
  components/modules/i2c.c
  components/modules/i2c_common.h
  components/modules/i2c_hw_master.c
  docs/modules/i2c.md
Labels: ESP32, bugfix

#3384 Doc update for bme280.lua
  docs/lua-modules/bme280.md
Labels: documentation, enhancement
