Repository nodemcu/nodemcu-firmware, pull requests merged in 2022-01, with the labels that each got.

#3487 Support interface-specific hostname on ethernet interface.
  components/modules/eth.c
  docs/modules/eth.md
Labels: ESP32

#3481 Consider RMT channel limitations at allocation time.
  components/platform/dht.c
  components/platform/include/platform_rmt.h
  components/platform/onewire.c
  components/platform/platform_rmt.c
  components/platform/ws2812.c
Labels: bugfix, ESP32

#3489 docs: node: point at telnet module now
  docs/modules/node.md
Labels: documentation

#3491 Fixing several typos
  app/uzlib/uzlib_deflate.c
  app/uzlib/uzlib_inflate.c
  docs/lcd.md
  docs/lfs.md
  docs/lua-developer-faq.md
  docs/lua53.md
  docs/spiffs.md
  tools/spiffsimg/README.md
Labels: documentation

#3500 Make UART buffer sizes configurable.
  components/platform/Kconfig
  components/platform/include/cpu_esp32.h
  components/platform/include/platform.h
  components/platform/platform.c
Labels: new feature, ESP32

#3496 Give the SPI module a chance of working...
  components/modules/spi_master.c
  docs/modules/spi.md
Labels: bugfix, ESP32

#3499 Fix build for WSL users
  Makefile
Labels: bugfix
