Repository nodemcu/nodemcu-firmware, pull requests merged in 2022-12, with the labels that each got.

#3561 Fix Typo in ds18b20-web.lua
  lua_modules/ds18b20/ds18b20-web.lua
Labels: bugfix

#3562 Make sodium.random API behave consistently on all build types
  components/modules/sodium.c
  docs/modules/sodium.md
Labels: enhancement, bugfix, ESP32

#3415 app/lua53: catch up to lua 5.3.6
  app/lua53/host/liolib.c
  app/lua53/lapi.c
  app/lua53/lauxlib.c
  app/lua53/lcode.c
  app/lua53/ldebug.c
  app/lua53/llex.c
  app/lua53/lobject.c
  app/lua53/lparser.c
  app/lua53/lua.h
  app/lua53/lundump.c
Labels: enhancement
