Repository nodemcu/nodemcu-firmware, pull requests merged in 2024-02, with the labels that each got.

#3568 Add support for using multiple memory slots in rmt setup
  components/modules/rmt.c
  docs/modules/rmt.md
  mkdocs.yml
Labels: new feature, ESP32

#3392 Add support for open networks to enduser_setup
  app/modules/enduser_setup.c
  docs/modules/enduser-setup.md
Labels: bugfix

#3629 Update rmt translator
  components/modules/ws2812.c
  components/platform/include/platform.h
  components/platform/ws2812.c
  docs/modules/ws2812.md
Labels: bugfix, ESP32

#3638 Fifo fixes
  lua_modules/fifo/fifo.lua
  lua_modules/fifo/fifosock.lua
Labels: bugfix
